const defaultConfig = 
  {
    "ADMIN_PASSWORD": "508058",
    "API_CLIENT_ID": "69f",
    "API_CLIENT_SECRET": "9ef",
    "ASSISTED_PAYMENT": {
        "ASSISTED_PAYMENT_PASSWORD": "508058",
        "USES_ASSISTED_PAYMENT": "false"
    },
    "BLOCK_TOTEM_ON_PRINT_ERROR": "false",
    "BLOCK_TOTEM_WHEN_PDV_UNABLE": "false",
    "BUFFET_DISH_PRICE": "0",
    "BUFFET_LIMIT": "0",
    "BUFFET_MENU_REDIRECT": "1",
    "BUFFET_MULTIPLE_DISHES": "0",
    "BUFFET_NAME": "Buffet",
    "BUFFET_PRICE": "0",
    "BUFFET_PRODUCT_ID": "1",
    "COLLECT_CPF": "false",
    "COLLECT_CPF_CNPJ": "true",
    "COLLECT_CPF_CNPJ_FIDELITY_SCORE": "false",
    "COLLECT_CPF_CNPJ_LABEL": "Informe seu CPF/CNPJ",
    "COLLECT_CPF_CNPJ_LABEL_HINT": "",
    "COLLECT_CPF_CNPJ_REQUIRED": "false",
    "COLLECT_CPF_LABEL": "Informe seu CPF",
    "COLLECT_CPF_LABEL_HINT": "",
    "COLLECT_CPF_REQUIRED": "false",
    "COLLECT_EMAIL": "false",
    "COLLECT_EMAIL_LABEL": "Qual seu e-mail?",
    "COLLECT_EMAIL_LABEL_HINT": "Qual seu e-mail?",
    "COLLECT_EMAIL_REQUIRED": "false",
    "COLLECT_NAME": "false",
    "COLLECT_NAME_AMOUNT_OF_CHARACTERS": "0",
    "COLLECT_NAME_LABEL": "Qual seu nome?",
    "COLLECT_NAME_LABEL_HINT": "",
    "COLLECT_NAME_REQUIRED": "false",
    "COLLECT_NAME_TYPE": "text",
    "COLLECT_PHONE": "false",
    "COLLECT_PHONE_LABEL": "Insira seu telefone.",
    "COLLECT_PHONE_LABEL_HINT": "Informe seu telefone para receber atualizações do seu pedido.",
    "COLLECT_PHONE_REQUIRED": "false",
    "COLLECT_QUESTIONS_ONLY_ACCEPT_TERMS": "",
    "COLLECT_TABLE": "false",
    "COLLECT_TABLE_LABEL": "Retire um pager no suporte ao lado:",
    "COLLECT_TABLE_LABEL_HINT": "Insira o número do seu pager e selecione confirmar.",
    "COLLECT_TABLE_MAXSIZE": "2",
    "COLLECT_TABLE_MINSIZE": "1",
    "COLLECT_TABLE_REQUIRED": "true",
    "COLLECT_TABLE_TYPE": "number",
    "COMBO_BRAND_CODE": "63407",
    "CONTINGENCY_PRINT_NO_FISCAL": {
        "LAYOUT": "kitchen",
        "NAME_PRINTER_MODEL": "",
        "PRINTER_URL": "",
        "PRINT_ON_PRINTER_ERROR": "false"
    },
    "CUSTOM_STEP_INTEGRATING ": {
        "SUBTITLE": "Pedido realizado!\nAgora estamos enviando sua lista para nossa equipe começar a preparar seu pedido.",
        "TITLE": "Enviando o seu pedido para nossa cozinha!",
        "USES_CUSTOM_ICON": "false"
    },
    "DEMO_MODE": "false",
    "DOCK": [],
    "ECO_FRIENDLY": {
        "HIDDEN_QUEUE_NUMBER": "",
        "SHOW_DEFAULT_LAYOUT": "",
        "SHOW_STEP_COUPON_CONFIRM": "",
        "SHOW_STEP_FINISH": "",
        "USES_ECO_FRIENDLY": ""
    },
    "ENVIRONMENT": "AWS",
    "FACIAL_RECOGNITION": "0",
    "FIDELITY": {
        "APPLY_CASHBACK_ON_THE_ORDER": "true",
        "BACK_LABEL": "Não obrigado",
        "CREDIT_PREFIX": "GRFF$",
        "FACIAL_RECOGNITION": "0",
        "FIDELITY_API_KEY": "503ef87d70e78f99e8ebd3f0ebd495dd",
        "FIDELITY_API_URL": "https://www.gcom.com.br/wsrest/api",
        "FIDELITY_CLIENT_ID": "9323ba0a-c41d-45d2-ba0f-704c29e4dc91",
        "FIDELITY_CLIENT_SECRET": "Dq+P&j6SfZzAJ7#xKC43Lau@AvP$J-KjHRcxuNhc+Zkxg57xLz",
        "FIDELITY_IN_LOJIST_MENU": "false",
        "FIDELITY_MARK_ID": "219",
        "FIDELITY_MAX_PERCENTAGE": "20",
        "FIDELITY_PROGRAM": "trigo-v2",
        "FIDELITY_PROGRAM_TITLE": "Fidelidade Giraffas",
        "FIDELITY_QRCODE_REGISTRATION_URL": "https://www.spoleto.com.br/fidelidade",
        "FIDELITY_STORE_ID": "4580",
        "MESSAGE_BAR_NOT_COMPLETE": "Cadastre-se no site para usar os benefícios do programa de fidelidade Giraffas!",
        "MESSAGE_BAR_NOT_IDENTIFIED": "Cadastre-se no site para usar os benefícios do programa de fidelidade Giraffas!",
        "MESSAGE_BAR_NOT_REGISTERED": "Cadastre-se no site para usar os benefícios do programa de fidelidade Giraffas!",
        "PAGE_END_FIDELITY_CASHBACK_COLOR ": "#000000",
        "PAGE_END_FIDELITY_DESCRIPTION": "",
        "PAGE_END_FIDELITY_SUBTITLE": "",
        "PAGE_END_FIDELITY_TITLE": "",
        "PAGE_FIDELITY_DESCRIPTION": "",
        "PAGE_FIDELITY_SUBTITLE": "DIGITE SEU TELEFONE PARA ACUMULAR CASHBACK NESSA COMPRA!",
        "PAGE_FIDELITY_TITLE": "Faça parte do Fidelidade Giraffas",
        "SCORE_PREFIX": "",
        "SCORE_SUFFIX": "",
        "SHOW_ONLY_PRODUCT_WITH_SUFFICIENT_SCORE": "0",
        "SUBTITLE_MESSAGE_CATEGORY_FIDELITY_WITHOUT_PRODUCT": "Continue comprando com a gente para acumular pontos no Fidelidade e volte aqui na próxima vez!",
        "TITLE_MESSAGE_CATEGORY_FIDELITY_WITHOUT_PRODUCT": "Você ainda não tem pontos suficientes para resgatar nenhum produto :(",
        "USE_FIDELITY": "0",
        "USE_FIDELITY_OLGA ": "0",
        "USE_SCORE": "0",
        "WEBCAM_ANGLE": "0"
    },
    "FILTER_BY_TAG": "true",
    "IMG_REPLACE_FULL_BANNER": "",
    "INITIAL_CHOICE": {
        "ICON_EAT_HERE_URL": "",
        "ICON_TO_CARRY_URL": "",
        "MESSAGE_INFO_EAT_HERE": "",
        "MESSAGE_INFO_TO_CARRY": "Embalagem Prato R$ 4,00",
        "PACKING_DEFAULT": "",
        "QTD_ITENS_ON_PACKING_DEFAULT": "1",
        "SHOW_INITIAL_CHOICE": "true",
        "TEXT_BUTTON_EAT_HERE": "",
        "TEXT_BUTTON_TO_CARRY": ""
    },
    "INTEGRATION_ATTEMPS": "3",
    "INTEGRATION_ERROR_BACK_TO_PAYMENT": "false",
    "INTEGRATION_WAIT": "30000",
    "LAST_IMG_TIMEOUT": "12000",
    "LOCK_SCREEN_PENDING_INTEGRATION": {
        "LOCK_SCREEN_GUIDING_TEXT": "Entre em contato com a franqueadora",
        "LOCK_SCREEN_PASSWORD": "123456",
        "LOCK_SCREEN_SHOW": "false"
    },
    "MENU_LOJIST": {
        "SUBTITLE_MESSAGE": "MENSAGEM DE SUBTITULO",
        "TEXT_ALERT_MENU_DEFAULT": "Comum",
        "TEXT_ALERT_MENU_LOJIST": "Lojista",
        "TEXT_BUTTON_MENU_DEFAULT": "CARDAPIO COMUM",
        "TEXT_BUTTON_MENU_LOJIST": "CARDAPIO LOJISTA",
        "TITLE_MESSAGE": "TITULO DA TELA DE ESCOLHA",
        "USES_MENU_LOJIST": "0"
    },
    "MESSAGE_INTEGRATION_ERROR": "Dirija-se até o caixa e apresente este comprovante para confirmar o seu pedido",
    "MULTIPLE_PRODUCT_SYNC_URL": "",
    "MULTIPLE_STORES": "0",
    "NAME_PRINTER": "epson-t88",
    "PARTNER_AUTH_PASSWORD": "",
    "PARTNER_AUTH_USER": "",
    "PARTNER_ESTABLISHMENT_CODE": "",
    "PARTNER_INTEGRATION_CODE": "",
    "PARTNER_KEY": "503ef87d70e78f99e8ebd3f0ebd495cc",
    "PARTNER_NAME": "gcom-spoleto",
    "PARTNER_RETURN_FISCAL": "true",
    "PARTNER_RETURN_FISCAL_URL": "",
    "PARTNER_URL": "http://WKS-GBOURBON-01.local",
    "PAYMENT": {
        "BANNER_CARD_LIST": "master, visa, elo, greencard, avista, valecard, vr, verocard, up, goodcard, americanexpress, hipercard, cabal, ticket, sodexo, alelo, sicred, jbc",
        "CASHIER_GUIDE": "Dirija-se ao caixa para efetivar o seu pedido",
        "CASHIER_GUIDE_PRINTER": "Dirija-se ao caixa para pagar o seu pedido",
        "CASHIER_NAME_LABEL": "Pagar no caixa",
        "CASHIER_SHOW_ORDER_QRCODE": "true",
        "MULTIPLE_CARDS_ACCEPTED_PAYING_METHODS": "credito, debito",
        "MULTIPLE_CARDS_BUTTON_LABEL": "Dividir a conta",
        "MULTIPLE_CARDS_ENABLED": "false",
        "MULTIPLE_CARDS_TITLE": "Quer rachar ou dividir a conta?",
        "PAYMENT_METHOD": "credito, debito, voucher, pixsitef",
        "VOUCHER_ALLOWED_TYPES": "alimetacao",
        "VOUCHER_NAME_LABEL": "Vale Refeição"
    },
    "PERSONA_OFFER_CATEGORY_DESCRIPTION": "Categoria personalizada para você!",
    "PERSONA_OFFER_CATEGORY_NAME": "Sugestões de produtos",
    "PERSONA_RECOGNIZE": "false",
    "PRE_URL_FIND_CONFIG": "",
    "PRINT_CPF_CNPJ_ON_THE_INVOICE": "false",
    "PRINT_EXTRA": [],
    "PRINT_EXTRA_WS_URL": "",
    "PRINT_LAYOUT": "vs-qrcode-image-password",
    "PRINT_NO_FISCAL_LAYOUT": "default-details",
    "PRINT_ORDER_WITHOUT_INTEGRATION_ID": "",
    "PRINT_TEF_LATER": "1",
    "PRODUCT_DETAILS_QT_CONTROL": "true",
    "QUEUE_BY_QRCODE": {
        "MESSAGE": "Leia o QR Code apontando a câmera do seu smartphone",
        "SOURCE": "partner_fiscal_response",
        "STATUS": "true",
        "TITLE": "Atenção!\n",
        "USE_PARTNER_MESSAGE": "true"
    },
    "QUEUE_TICKET_WS": {
        "URL_QUEUE_TICKET_WS": "https://queue.api.food.vsd.app/",
        "USE_QUEUE_TICKET_WS": "0"
    },
    "SALE_SEQUENCE_START_NUMBER": "",
    "SHOW_TEF_SUCCESS_MSG": "",
    "STORE_NAME": "",
    "STORE_SYNC_URL": "",
    "TEF_PASSWORD_ADMIN": "508058",
    "TERMINAL_TEXTS": {
        "BEGIN_DESCRIPTION": "Selecione o restaurante onde gostaria de fazer seu pedido",
        "BEGIN_TITLE": "ONDE VOCÊ QUER COMER?",
        "CANCEL_ORDER_AND_CHANGE_STORE_CANCEL_BUTTON": "Cancelar seu pedido e alterar restaurante",
        "CANCEL_ORDER_CHANGE_STORE_IN_BANNER_BUTTON": "Trocar restaurante",
        "CANCEL_ORDER_CONTINUE_BUTTON": "Continuar com meu pedido atual",
        "CANCEL_ORDER_DESCRIPTION": "Não é possível fazer pedidos em mais de um estabelecimento simultaneamente",
        "CANCEL_ORDER_TITLE": "Cancelar seu pedido atual e escolher outro restaurante?"
    },
    "TIMEOUT_APLICATION": "60000",
    "TIMEOUT_PAYMENT_AUTOPAGSE": "240000",
    "TIMEOUT_PAYMENT_AUTOPAGSE_MULTIPLE": "",
    "TIPPING_PERCENTAGE": "",
    "TIPPING_SUGGESTION": "false",
    "URL_ITEGRATION_ERP": "",
    "USES_INTEGRATION": "true",
    "USES_PRE_SALE": "false",
    "USES_QUEUENUMBER_FISCAL_NOTE": "false",
    "USES_VIRTUAL_KEYBOARD": "false",
    "USES_VS_PRINT": "true",
    "USES_WAITER_CALL_BUTTON": "false",
    "USE_COUPON": "false",
    "USE_COUPON_MESSAGE_INSERT": "INSIRA SEU CUPOM ",
    "USE_COUPON_MESSAGE_INSTRUCTION": "OLÁ TEM UM CUPOM?",
    "USE_PRINTER_BY_INTERFACE": "true",
    "USE_VS_DOCK": "true",
    "VERIFY_CATALOG_AT_END": "1",
    "VERIFY_CATALOG_INTERVAL": "3600000",
    "VS_PEDIDOS_API_URL": "",
    "WEBCAM_ANGLE": "90",
    "__DOCK": {
        "APPS": [
            {
                "img": "",
                "name": "",
                "url": ""
            }
        ]
    },
    "__PRINTER_CONTINGENCY": {
        "HEADER_MESSAGE_SUBTITLE": "Não foi possível imprimir seu comprovante, por isso ele será disponibilizado digitalmente.",
        "HEADER_MESSAGE_TITLE": "Impressora indisponível no momento.",
        "SHOW_BUTTON_CONFIRM": "true",
        "STEP_ERROR_PRINTER": {
            "INSTRUCTION_TEXT": "'Informe sua senha acima para um de nossos atendentes para finalizar o seu pedido",
            "ORDER_MESSAGE_ERROR": "Por favor, siga as instruções abaixo:",
            "SUBTITLE_MESSAGE_ERROR": "Ocorreu um erro e seu pedido não chegou na nossa cozinha"
        },
        "TEXT_BUTTON_CONFIRM": "Confirmar",
        "TEXT_BUTTON_EMAIL": "Receber por e-mail",
        "TEXT_BUTTON_GET_DIGITAL_COUPON": "Meu comprovante",
        "TEXT_BUTTON_SMS": "Receber por SMS",
        "TEXT_INFORMATION_SUBTITLE": "Se preferir, você pode receber seus comprovantes por sms ou e-mail",
        "TEXT_INSERT_EMAIL": " Informando seu e-mail você poderá receber seu comprovante fiscal digitalmente.",
        "TEXT_INSERT_PHONE": " Informando seu telefone você poderá receber seu comprovante fiscal digitalmente.",
        "TEXT_SUBTITLE_QRCODE": "Por favor, confirme que escaneou o QR Code e recebeu seu cupom fiscal.",
        "TIMEOUT_CHECK_PRINTER_STATUS": "",
        "TIMEOUT_INPUT_DOCUMENT": "",
        "TIMEOUT_PROGRESSBAR": "3e4",
        "TIMEOUT_STEP_PRINT_ERROR": "",
        "TITLE": "Escaneie o QR Code abaixo para receber seus comprovantes",
        "USES_EMAIL": "true",
        "USES_PRINTER_CONTINGENCY": "true",
        "USES_QRCODE": "true",
        "USES_SMS": "true"
    }
}

export default defaultConfig